# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for TelegramDownloader.app. Build with `make mac-app`.

Never add config.yaml, data.yaml or sessions here: they hold the builder's
own Telegram credentials and login.
"""
import os
import sys

ROOT = os.path.abspath(os.path.join(SPECPATH, "..", ".."))
sys.path.insert(0, ROOT)
from utils import __version__  # noqa: E402

a = Analysis(
    [os.path.join(ROOT, "gui_main.py")],
    pathex=[ROOT],
    binaries=[],
    datas=[
        (os.path.join(ROOT, "module", "templates"), "module/templates"),
        (os.path.join(ROOT, "module", "static"), "module/static"),
    ],
    # module.parsetab (generated by gen_filter_cache.py) is compiled in so ply finds
    # matching tables and never writes new ones into the signed bundle
    hiddenimports=["media_downloader", "module.controller", "module.web", "module.parsetab"],
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TelegramDownloader",
    console=False,
    argv_emulation=False,
    target_arch="arm64",
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(exe, a.binaries, a.datas, strip=False, upx=False, name="TelegramDownloader")
app = BUNDLE(
    coll,
    name="TelegramDownloader.app",
    icon=os.path.join(SPECPATH, "icon.icns"),
    bundle_identifier="io.github.guohai-zhang.telegram-media-downloader",
    version=__version__,
    info_plist={
        "CFBundleName": "TelegramDownloader",
        "CFBundleDisplayName": "Telegram 下载器",
        "CFBundleShortVersionString": __version__,
        "CFBundleVersion": __version__,
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
    },
)
